### ISSUE TITLE
How do the reducers operate on it's particular part of the state?

### ISSUE THREAD

**Issue by cbelden** [lukewestby/jschi-react-demo#1]
Hi Luke,

I would have thought that each reducer accepts the entire, current state and returns a new, entire state. Looking at the reducers, however, it looks like the state parameter passed in is only part of the entire state.

For example, let's pretend the entire state consists of:

``` javascript
AppState = {
    comments: [],
    commentText: '',
    errorMessage: ''
}
```

And each reducer only operates on the part of the state that it pertains to. Here's the comments text reducer for reference (I'm assuming in this case, the `state` argument will actually be the `AppState.comments` property):

``` javascript
export default function comments(state = [], action) {
  switch(action.type) {

  case LOAD_COMMENTS_SUCCESS:
    return action.comments;

  case CREATE_COMMENT_SUCCESS:
    return state.concat(action.comment);

  default:
    return state;
  }
}
```

 How does redux (or the developer) control what part of the state gets passed into the reducer?

**Comment by lukewestby** [comment]
In `src/reducers/index.js` we are associating a reducer with the name of the property it aggregates in the overall app state. This call here:

``` javascript
export default combineReducers({
  comments,
  commentText,
  errorMessage,
  loading
});
```

creates a new top level reducer which will associate the output of each individual reducer with the property name it's associated with. In this case, the `comments` reducer gets passed into the object for  `combineReducers` as the `comments` property, and so the `comments` property in the app state is controlled by that reducer.

**Comment by cbelden** [comment]
Thanks!
